name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    - run: npm ci
    - run: npm run test
